export const navigation = [
  {
    title: 'Index',
    links: [
      { title: 'Index', href: '/docs' },
    ],
  },
  {
    title: 'Introduction',
    links: [
      { title: 'Installation', href: '/docs/introduction/installation' },
      { title: 'Running', href: '/docs/introduction/running' },
    ],
  },
  {
    title: 'CLI',
    links: [
      { title: 'Overview', href: '/docs/cli/overview' },
      { title: 'check', href: '/docs/cli/check' },
      { title: 'connector', href: '/docs/cli/connector' },
      { title: 'dev', href: '/docs/cli/dev' },
      { title: 'delete', href: '/docs/cli/delete' },
      { title: 'down', href: '/docs/cli/down' },
      { title: 'env', href: '/docs/cli/env' },
      { title: 'exec', href: '/docs/cli/exec' },
      { title: 'init', href: '/docs/cli/init' },
      { title: 'logs', href: '/docs/cli/logs' },
      { title: 'output', href: '/docs/cli/output' },
      { title: 'purge', href: '/docs/cli/purge' },
      { title: 'refresh', href: '/docs/cli/refresh' },
      { title: 'status', href: '/docs/cli/status' },
      { title: 'test', href: '/docs/cli/test' },
      { title: 'up', href: '/docs/cli/up' },
      { title: 'version', href: '/docs/cli/version' },
    ],
  },
  {
    title: 'Resources',
    links: [
      { title: 'Overview', href: '/docs/resources/overview' },
      { title: 'Meta Properties', href: '/docs/resources/meta' },
      { title: 'Resource Functions', href: '/docs/resources/functions' },
      { title: 'Variables', href: '/docs/resources/variables' },
      { title: 'Output', href: '/docs/resources/output' },
      { title: 'Module', href: '/docs/resources/module' },
      { title: 'Blueprint', href: '/docs/resources/blueprint' },
      { title: 'Book', href: '/docs/resources/book' },
      { title: 'Build', href: '/docs/resources/build' },
      { title: 'Certificate', href: '/docs/resources/certificate' },
      { title: 'Chapter', href: '/docs/resources/chapter' },
      { title: 'Container', href: '/docs/resources/container' },
      { title: 'Copy', href: '/docs/resources/copy' },
      { title: 'Docs', href: '/docs/resources/docs' },
      { title: 'Helm', href: '/docs/resources/helm' },
      { title: 'Ingress', href: '/docs/resources/ingress' },
      { title: 'Kubernetes Cluster', href: '/docs/resources/kubernetes_cluster' },
      { title: 'Kubernetes Config', href: '/docs/resources/kubernetes_config' },
      { title: 'Leaf Certificate', href: '/docs/resources/certificate_leaf' },
      { title: 'Local Exec', href: '/docs/resources/local_exec' },
      { title: 'Network', href: '/docs/resources/network' },
      { title: 'Nomad Cluster', href: '/docs/resources/nomad_cluster' },
      { title: 'Nomad Job', href: '/docs/resources/nomad_job' },
      { title: 'Output', href: '/docs/resources/output' },
      { title: 'Random ID', href: '/docs/resources/random_id' },
      { title: 'Random Number', href: '/docs/resources/random_number' },
      { title: 'Random Password', href: '/docs/resources/random_password' },
      { title: 'Random UUID', href: '/docs/resources/random_uuid' },
      { title: 'Remote Exec', href: '/docs/resources/remote_exec' },
      { title: 'Root Certificate', href: '/docs/resources/certificate_ca' },
      { title: 'Sidecar', href: '/docs/resources/sidecar' },
      { title: 'Task', href: '/docs/resources/task' },
      { title: 'Template', href: '/docs/resources/template' },
    ]
  }
]